baseurl = "yunasnovela.github.io"
title = "DantonKoto"
copyright = "Copyright &copy; 2017 - Author Name"
canonifyurls = false
theme = "hugo-kiera"

paginate = 5

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "yunasnovela"
    github = "yunasnovela"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "Sedikit berbagi pengalaman di bidang Open Source GNU/Linux"


